Epedemic Analysis and Visualization/Epedemic Analysis and Visualization/urls.py
from django.conf.urls import url , include
from django.contrib import admin
from map.views import special , user_logout

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^map/', include('map.urls')),
    url(r'^user_logout/',user_logout,name  = "user_logout"),
    url(r'^special/',special,name = "special"),

]

Epedemic Analysis and Visualization/map/urls.py
from django.conf.urls import url
from map import views

app_name = 'map'

urlpatterns = [


    url(r'^register/',views.register,name='register' ),
    url(r'^index/',views.index,name='index' ),
    url(r'^user_login/',views.user_login,name='user_login' ),
    url(r'^eav/',views.eav,name = "eav"),
    url(r'^parameters/',views.para_view,name = "para_view"),




]

Epedemic Analysis and Visualization/map/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.


class UserProfileInfo(models.Model):
	user = models.OneToOneField(User)
	portfolio_site = models.URLField(blank=True)
	profile_pic = models.ImageField(upload_to = 'profile_pics',blank = True )


	def __str__(self):
		return self.user.username




#========================= Parameters ==============================

class Parameters(models.Model):
	infection_rate = models.FloatField(null = True)
	recovery_rate  = models.FloatField(null = True)
	upload_file    = models.FileField(upload_to = 'profile_pics' , blank = False)




#======================= Simulation ===============================


class SIR(models.Model):
	lat = models.FloatField(null = True)
	lng = models.FloatField(null = True)
	counter = models.IntegerField(null = True)
	date = models.DateField(auto_now = False)

	

Epedemic Analysis and Visualization/map/forms.py
from django import forms
from django.contrib.auth.models import User
from map.models import UserProfileInfo , Parameters


class UserForm(forms.ModelForm):
	password = forms.CharField(widget = forms.PasswordInput(attrs={'class':'form-control','placeholder':'Password'}))
	username = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'username'}))
	email = forms.EmailField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Email'}))

	class Meta():
		model = User
		fields = ('username','email','password')



class UserProfileInfoForm(forms.ModelForm):
	portfolio_site = forms.URLField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'website url'}))

	class Meta():
		model = UserProfileInfo
		fields = ('portfolio_site','profile_pic')


# ================== Parameter form ======================


class ParameterForm(forms.ModelForm):

	class Meta():
		model = Parameters
		fields = '__all__'
		 

Epedemic Analysis and Visualization/map/views.py
from django.shortcuts import render
from map.forms import UserForm, UserProfileInfoForm , ParameterForm
from django.core .urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect , HttpResponse
from django.contrib.auth import authenticate , login , logout
from map.models import Parameters , SIR
import json
import random
import numpy as np
from bisect import bisect_left
from bisect import bisect_right
import math
from collections import deque
import os




def index(request):
	return render(request,'map/index.html')




def register(request):

	registered = False

	if request.method == 'POST':
		user_form = UserForm(data = request.POST)
		profile_form = UserProfileInfoForm(data = request.POST)

		if user_form.is_valid() and profile_form.is_valid() :

			user = user_form.save()
			user.set_password(user.password)
			user.save()

			profile = profile_form.save(commit = False)
			profile.user = user 

			if 'profile_pic' in request.FILES:
				profile.profile_pic = request.FILES['profile_pic']


			profile.save()

			registered = True

		else:
			print(user_form.errors , profile_form.errors)
	else:

		user_form = UserForm()
		profile_form = UserProfileInfoForm()


	return render(request,'map/registeration.html', {'user_form':user_form,'profile_form':profile_form,'registered' : registered})




@login_required
def user_logout(request):
	logout(request)
	return HttpResponseRedirect(reverse("map:index"))			



@login_required
def special(request):
	return HttpResponse("Hey Bro special !")



def user_login(request):

	if request.method == 'POST':
		username = request.POST.get('username')
		password = request.POST.get('password')

		user = authenticate(username = username , password = password)

		if user :
			if user.is_active:
				login(request,user)
				return HttpResponseRedirect(reverse("map:eav"))			
			else:
				return HttpResponse("User is not Active")
		else:
			return HttpResponse("User Login Failed !")
	else:
		return render(request,'map/login.html')



def eav(request):
	context = {"SIR" : SIR.objects.all() , "range" : range(10)}

	return render(request,'map/eav.html',context)


# =============== parameter_view ====================


def para_view(request):

	if request.method == 'POST':

		para_form = ParameterForm(request.POST , request.FILES)

		if para_form.is_valid():

			para_form.save()
			printfun()
			return HttpResponseRedirect(reverse("map:eav"))				

	else:

		para_form = ParameterForm()

	return render(request,'map/parameter.html', {'para_form':para_form})




def remove(arr1,arr2):
    for i in range(len(arr1)):
        arr2=np.delete(arr2,arr1[i]-i)
    return arr2


# In[9]:

def include(susceptable_pop_lat,susceptable_pop_lng ,inf,rinf):
    for values in rinf:
        inf.append([susceptable_pop_lat[values][0],susceptable_pop_lng[values][0]])
    return inf


# In[10]:

def distance(a,b):
    return math.sqrt((a[0]-b[0])**2+(a[1]-b[1])**2)


# In[11]:

def increment_date(dd,mm,yy):
    dd+=1
    if dd>30:
        mm+=1
        dd=1
    if mm>12:
        mm=1
        yy+=1
    return dd,mm,yy
    



def printfun():

	p = Parameters.objects.all()

	json_file = json.loads(p[0].upload_file.read())

	mainlist=[]
	for lines in json_file:   
	    mainlist.append([lines["lat"],lines["lng"]])
	
	mainlist.sort(key=lambda x:x[0])


	#=============================== Redundent data removal =================================
	i=0
	deleted=0
	while i<len(mainlist):
	    if mainlist[i-1]==mainlist[i]:
	        mainlist.remove(mainlist[i])
	        deleted+=1
	    else:
	        i+=1

	#print(len(mainlist))

	longitude=[]
	latitude=[]
	for i in range(len(mainlist)):
	    latitude.append(mainlist[i][0])
	    longitude.append(mainlist[i][1])

	#print(len(longitude))


	# # initialising the data

	# In[3]:


	susceptable_pop_lat=np.array(latitude)   #np.random.randint(1,100,(10000))
	susceptable_pop_lng=np.array(longitude)    #np.random.randint(1,100,(10000))

	threshold=0.1
	initiallyinfected=np.random.randint(0,len(json_file)-1,size=(2,1))
	infected=deque()
	recovered=[]
	counter=deque()

	mpd=0


	# In[4]:

	# # initialising the date

	# In[5]:


	dd=1
	mm=1
	yy=2015


	# In[6]:


	recover=5


	# In[7]:


	initiallyinfected=np.sort(initiallyinfected,axis=0)

	infected=include(susceptable_pop_lat,susceptable_pop_lng,infected,initiallyinfected)
	susceptable_pop_lat=np.delete(susceptable_pop_lat,initiallyinfected)
	susceptable_pop_lng=np.delete(susceptable_pop_lng,initiallyinfected)
	counter+=[0]*len(infected)



	# In[13]:



	for i in range(len(infected)):
	    valued='{\ncounter: 0 ,\n'
	    date='date : '+str([yy,mm,dd])+',\n'
	    coords='coords : '+str([infected[i][0],infected[i][1]])+'\n}\n'
	    data=valued+date+coords
	    s = SIR()
	    s.lat = infected[i][0]
	    s.lng = infected[i][1]
	    s.counter = 0
	    s.date = str(yy)+"-"+str(mm)+"-"+str(dd)
	    s.save()

	while len(infected)>0:
	    
	    dd,mm,yy=increment_date(dd,mm,yy)
	    
	    recent_infection=[]
	    for i in range(len(infected)):
	        
	        for j in range(len(susceptable_pop_lat)):
	            
	            dist=distance(infected[i],[susceptable_pop_lat[j],susceptable_pop_lng[j]])
	            
	            if dist<=threshold:
	                
	                probablity=np.random.random()
	                
	                if probablity>0.5:
	                    recent_infection.append(j)
	                    
	    recent_infection=list(set(recent_infection))
	    counter=deque([val+1 for val in counter])
	    counter=counter+deque([0]*len(recent_infection))
	    
	    
	    for k in range(len(recent_infection)):
	        infected.append([susceptable_pop_lat[recent_infection[k]],susceptable_pop_lng[recent_infection[k]]])
	        #entering the data of recently infected population in the file
	        valued='{\ncounter: 0 ,\n'
	        date='date : '+str([yy,mm,dd])+',\n'
	        coords='coords : '+str([susceptable_pop_lat[recent_infection[k]],susceptable_pop_lng[recent_infection[k]]])+'\n}\n'
	        data=valued+date+coords
	        s = SIR()
	        s.lat = infected[k][0]
	        s.lng = infected[k][1]
	        s.counter = 0
	        s.date = str(yy)+"-"+str(mm)+"-"+str(dd)
	        s.save()
	    
	    susceptable_pop_lat=np.delete(susceptable_pop_lat,recent_infection)
	    susceptable_pop_lng=np.delete(susceptable_pop_lng,recent_infection)
	    recovering=0
	    for l in range(len(counter)):
	        if counter[l]>=recover:
	            recovering+=1
	        else:
	            break
	    for l in range(recovering):
	        coordinates=infected.popleft()
	        valued='{\ncounter: 1 ,\n'
	        date='date : '+str([yy,mm,dd])+',\n'
	        coords='coords : '+str(coordinates)+'\n}\n'
	        data=valued+date+coords
	        s = SIR()
	        s.lat = coordinates[0]
	        s.lng = coordinates[1]        
	        s.counter = 1
	        s.date = str(yy)+"-"+str(mm)+"-"+str(dd)
	        s.save()
	        recovered.append(coordinates)
	        counter.popleft()

	    print("Total Susceptable Recent Infection  Total Infected     Total Recovered Date")
	    print(len(susceptable_pop_lat) ,len(recent_infection),len(infected),len(recovered),str([yy,mm,dd]))
	            

Epedemic Analysis and Visualization/templates/map/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head>

		<!-- <link rel="stylesheet" type="text/css" href="{% static 'style1.css' %}">
 -->
		<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
	        <!-- Latest compiled and minified CSS -->
	    <!-- <script type="text/javascript" src='{% static "data.json" %}'></script>
 -->

       <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

        <!-- jQuery library -->
       <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

        <!-- Latest compiled JavaScript -->
       <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script> 

       <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>

        <script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDxf3Ej_V1-WWod0-RN4XciwULYtL6yXh0&libraries=visualization">
      </script>

	   <title>Base</title>





</head>
<body>

	<nav class="navbar navbar-default navbar-static-top" id="nav_image">
		<div class="container-fluid">
			<div class="navbar-header">
				<a href="{% url 'map:index' %}"  class="navbar-brand">EPDA</a>
			</div>
			<ul class="nav navbar-nav navbar-right">

				<li class="navbar-link"><a href="{% url 'admin:index' %}"><span class="glyphicon glyphicon-log-in"></span> Admin Login</a></li>
				<li class="navbar-link"><a href="{% url 'map:register' %}"><span class="glyphicon glyphicon-user"></span> Register</a></li>
				<li class="navbar-link"><a href="{% url 'map:para_view' %}"><span class="glyphicon glyphicon-plus-sign"></span> Add Simulation Parameters</a></li>
				<li class="navbar-link"><a href="{% url 'map:eav' %}"><span class="glyphicon glyphicon-camera"></span> Simulation Result</a></li>

				{% if user.is_authenticated %}

				<li class="navbar-link"><a href="{% url 'user_logout' %}"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>

				{% else %}

				<li class="navbar-link"><a href="{% url 'map:user_login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>

				{% endif %}



			</ul>
		</div>

		
	</nav>

	<div class="container">
		{% block body_block %}
	    {% endblock %}
		
	</div>



</body>
</html>

Epedemic Analysis and Visualization/templates/map/eav.html
{% load staticfiles %}


<!DOCTYPE html >
<html>
  <head>
      

       <meta charset="utf-8">

        <title>Heatmaps</title>

       <script type="text/javascript" src='{% static "data.json" %}'></script>
        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

        <!-- jQuery library -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

        <!-- Latest compiled JavaScript -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script> 

        <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>

       

    <!-- =======================Google Map Javascript API ======================== -->

    <!-- ====================== Google Map API Key ============================ -->
      <script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDxf3Ej_V1-WWod0-RN4XciwULYtL6yXh0&libraries=visualization">
      </script>

      





      <link rel="stylesheet" type="text/css" href='{% static "style.css" %}'>


  </head>

  <body>


    <!-- ===================== Color Changing Heading  =====================-->

<div class="jumbotron jumbotron-fluid" id="background">

  <div class="row" >
      <center><h2 id="heading">Epidemic Analysis and Visualization </h2></center>

  </div>

  <div class="row">
    <center><p id="result">Select The Option Below</p></center>
    
  </div>

  <div class="row">
    
    <div class="col-xs-6">
      <center><button class="btn btn-success btn-lg" id="pie">Pie Chart</button></center>

    </div>
    <div class="col-xs-6">
     <center><button class="btn btn-primary btn-lg" id="start">Show Map</button></center>

    </div>
  </div>

</div>
        
  <div class="row">

 

 <!-- ========================== PIE CHart ============================== -->
        <div class="col-xs-5">
           <div id="piechart"></div>

        </div>
  



  <!-- ================= Map Division=================-->

        <div class="col-xs-7">
          
          <div id="map"></div>
        </div>


 </div>

 <script type="text/javascript">
   
   // =====================================. query selector =================================

header = document.querySelector("#heading");
start = document.querySelector("#start");
pie = document.querySelector("#pie");
result = document.querySelector("#result");


//=================================== Variables ==========================================

var map, heatmap,mvc , mvcR;
var numDeltas = 10;
var delay = 10; //milliseconds
var i =0;
var data;
var count1 = 0 ,count2 = 0;
var heatmap,heatmap1;
var length = {{SIR|length}}
var arr1 = new Array();


{% for sir in SIR %}
  
    arr1.push([{{sir.lng}} , {{sir.lat}}, {{sir.counter}}])

{% endfor %}

console.log(arr1[0][0],arr1[0][1]);

//   ============================= Color Changing Function =====================
function getRandomColor() {
  var letters = '0123456789ABCDEF';
  var color = '#';
  for (var i = 0; i < 6; i++) {
    color += letters[Math.floor(Math.random() * 16)];
  }
  return color;
}


function setColor()
{
  header.style.color = getRandomColor();
  result.style.color = getRandomColor();
  

}


setInterval(setColor,500);


// ===============================Map Event Listerner=============================================

start.addEventListener('click',initMap);


// ====================== Map Fuction ============================================================

function initMap() {
        map = new google.maps.Map(document.getElementById('map'), {
          zoom: 10,
          center: {lat: arr1[100][0], lng: arr1[100][1]},
          mapTypeId: 'satellite'
        });


    mvc = new google.maps.MVCArray();
    mvcR = new google.maps.MVCArray()

           // ================== Infection heatmap =============================
        heatmap = new google.maps.visualization.HeatmapLayer({
                    data: mvc,
                     map: map,
                     radius : 10


                    });

        // ================== Recovery heatmap =============================
        heatmap1 = new google.maps.visualization.HeatmapLayer({
                     data: mvcR,
                     map: map,
                     radius : 10,
                     gradient : [
                                    'rgba(0, 0, 0, 0)',
                                    'rgba(0, 255, 255, 1)',
                                    'rgba(0, 191, 255, 1)',
                                    'rgba(0, 127, 255, 1)',
                                    'rgba(0, 63, 255, 1)',
                                    'rgba(0, 0, 255, 1)',
                                    'rgba(0, 0, 223, 1)',
                                    'rgba(0, 0, 191, 1)',
                                    'rgba(0, 0, 159, 1)',
                                    'rgba(0, 0, 127, 1)',
                                    'rgba(63, 0, 91, 1)',
                                    'rgba(127, 0, 63, 1)',
                                    'rgba(191, 0, 31, 1)',
                                    'rgba(0, 0, 0, 1)'
                                  ]
                    });


        move();

          

       }


   function move()
        {

                  for(var k = i;k< i+5 && k < length;k++)
                  {
                        var cur = new google.maps.LatLng(arr1[k][0],arr1[k][1]);

                        if (arr1[k][2] == 0)
                        {
                           mvc.push(cur);
                           count1++;

                        } 

                        else
                        {
                          
                          mvcR.push(cur);
                          count2++;
                        }   
                    
                        
                   }





              i = k;
                         
                         // i = k;
                         if (i < length)
                         {                                                            
                            setTimeout(move,10); 
                         }
       }

 // =================================================== Map Function End ==================================

  // ============================================== Pie Chart Function ================================


  pie.addEventListener('click',function()
    {
        google.charts.setOnLoadCallback(drawChart); 
    });
 
      google.charts.load('current', {'packages':['corechart']});

       function drawChart() {



      var data = google.visualization.arrayToDataTable([
          ['No of people', 'Hours per Day'],        
          ['Saved', count2],
          ['Infected',     count1],

          ['Total',{{SIR|length }}]
          
        ]);

        var options = {
          title: 'Infection Activity'
        };

        var chart = new google.visualization.PieChart(document.getElementById('piechart'));


        chart.draw(data, options);
        data.setValue(0, 1,count1);
        data.setValue(1, 1,count2);
        setInterval(drawChart,5000)
      }


// ==================================== Color changing of  recovery map =========================================


function changeGradient() {
        var gradient = [
          'rgba(0, 0, 0, 0)',
          'rgba(0, 255, 255, 1)',
          'rgba(0, 191, 255, 1)',
          'rgba(0, 127, 255, 1)',
          'rgba(0, 63, 255, 1)',
          'rgba(0, 0, 255, 1)',
          'rgba(0, 0, 223, 1)',
          'rgba(0, 0, 191, 1)',
          'rgba(0, 0, 159, 1)',
          'rgba(0, 0, 127, 1)',
          'rgba(63, 0, 91, 1)',
          'rgba(127, 0, 63, 1)',
          'rgba(191, 0, 31, 1)',
          'rgba(0, 0, 0, 1)'
        ]
       
          heatmap1.set('gradient', heatmap1.get('gradient') ? null : gradient);

      }








 </script>
 
<!-- <script  type="text/javascript" src = '{% static "js/sir.js" %}'></script>  -->
<!-- <script type="text/javascript" src = '{% static "js/workerS.js" %}'></script>  -->

  </body>
</html>

Epedemic Analysis and Visualization/templates/map/index.html
{% extends "map/base.html" %}

{% block body_block %}

	<div class="jumbotron" id="jumb">
		<h3>Please Login For The HeatMap Visualization</h3>
		
	</div>

{% endblock %}

Epedemic Analysis and Visualization/templates/map/login.html
{% extends "map/base.html" %}

{% block body_block %}


		<div class="row">
			
			<div class="col-lg-3"></div>
			<div class="col-lg-6">
				<div class="jumbotron" id="jumb">
					<center>
						<h3 style="margin-bottom: 8%; color: #FF0000"> Login</h3>
						<form action={% url "map:user_login" %} enctype="multipart/form-data"  method="post">

						{% csrf_token %}
						<div class="form-group">
						<label for="username">Username:</label>
						<input type="text" name="username" placeholder="Enter username">
				
				</div>
				<div class="form-group">
					<label for="password">Password:</label>
					<input type="password" name="password">
				
				</div>
		
			<!-- <input type="submit" name="" value="Login"> 	 -->
				<button type="submit" class="btn btn-success">login</button>



			</form>

		</div>
	</center>

				
</div>

<div class="col-lg-3"></div>

</div>

		

{% endblock %}

Epedemic Analysis and Visualization/templates/map/parameter.html
{% extends "map/base.html" %}

{% load staticfiles %}

{% block body_block %}

<div class="row">
	<div class="col-lg-2"></div>
	<div class="col-lg-8">
	 	<div class="jumbotron" id="jumb">


			<center style="margin-bottom: 8%;">
				<h3 style="color: #FF0000">Enter Here!</h3>
				<h5>Fill out the parameters here</h5>
			</center>

			<form enctype="multipart/form-data" method="post">
<!-- 				{% for error in para_form.non_field_errors %}
                    <div class="form-group has-errors text-danger small">
                        {{error}}
                    </div>
                    {% endfor %}
                    {% for field in para_form %}
                    <div class="form-group has-errors text-danger small">
                        {{field.errors}}
                    </div>
                    <div class="form-group has-errors text-danger small">
                    </div>
                    <div class="form-group">

                        {{field}}
                    </div>
                 {% endfor %} -->

<!--                  {% for error in profile_form.non_field_errors %}
                    <div class="form-group has-errors text-danger small">
                        {{error}}
                    </div>
                    {% endfor %}
                    {% for field in profile_form %}
                    <div class="form-group has-errors text-danger small">
                        {{field.errors}}
                    </div>
                    <div class="form-group has-errors text-danger small">
                    </div>
                    <div class="form-group">

                        {{field}}
                    </div>
                 {% endfor %} -->

				{% csrf_token %}
				{{ para_form.as_p }}
				<!-- {{ profile_form.as_p }} -->

				<!-- <input type="submit" name="" value="register"> -->

				<button type="submit" class="btn btn-success btn-lg" id="alerting">Submit</button>
				
			</form>
				

	</div>
		

	</div>
	<div class="col-lg-2"></div>

</div>

<script>
    document.getElementById("alerting").alert("Please Wait Simulation is going on");


</script>



{% endblock %}

Epedemic Analysis and Visualization/templates/map/registeration.html
{% extends "map/base.html" %}

{% load staticfiles %}

{% block body_block %}

<div class="row">
	<div class="col-lg-3"></div>
	<div class="col-lg-6">
	 	<div class="jumbotron" id="jumb">

		{% if registered %}
			<h1>Thank you for registering</h1>
		
		{% else %}

			<center style="margin-bottom: 8%;">
				<h3 style="color: #FF0000">Register Here!</h3>
				<h5>Fill out the form here</h5>
			</center>

			<form enctype="multipart/form-data" method="post">
				{% for error in user_form.non_field_errors %}
                    <div class="form-group has-errors text-danger small">
                        {{error}}
                    </div>
                    {% endfor %}
                    {% for field in user_form %}
                    <div class="form-group has-errors text-danger small">
                        {{field.errors}}
                    </div>
                    <div class="form-group has-errors text-danger small">
                    </div>
                    <div class="form-group">

                        {{field}}
                    </div>
                 {% endfor %}

                 {% for error in profile_form.non_field_errors %}
                    <div class="form-group has-errors text-danger small">
                        {{error}}
                    </div>
                    {% endfor %}
                    {% for field in profile_form %}
                    <div class="form-group has-errors text-danger small">
                        {{field.errors}}
                    </div>
                    <div class="form-group has-errors text-danger small">
                    </div>
                    <div class="form-group">

                        {{field}}
                    </div>
                 {% endfor %}

				{% csrf_token %}
				<!-- {{ user_form.as_p }} -->
				<!-- {{ profile_form.as_p }} -->

				<!-- <input type="submit" name="" value="register"> -->

				<button type="submit" class="btn btn-success">register</button>
				
			</form>
				
	  {% endif %}	
	</div>
		

	</div>
	<div class="col-lg-3"></div>

</div>



{% endblock %}